gems:
  - jekyll-paginate
  - jekyll-feed

name: Innovantage
description: partnersko stvaranje korisnih proizvoda i usluga na globalnom tržištu
paginate: 5
paginate_path: "/blog/page:num/"
title: Innovantage

permalink: pretty

author:
  name: 'Nikola Balic'
  twitter_username: innovantage_eu
  linkedin_username:  nikola.balic
  skype: cheshipak
  
color:
  front: #FF4814
  hover: #B22D07
  back: #FF5B2D
  compl1: #00B27F
  compl2: #14FFBB
