---
title: Innovantage
timezone: Europe/Zagreb
url: https://www.innovantage.eu
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
gems:
- jekyll-paginate
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
name: Innovantage
description: partnersko stvaranje korisnih proizvoda i usluga na globalnom tržištu
keywords: innovantage, innovacije, istrazivanje, razvoj, financiranje, poduzetnistvo, innovation, IRI, RDI, savjetovanje
facebook: 
  app_id: 289513794769531
twitter:
  username: innovantage_eu
paginate: 5
paginate_path: "/blog/page:num/"
permalink: pretty
author:
  twitter: innovantage_eu
  name: "Nikola Balic"
  linkedin: nikola.balic
  skype: nikola.balic
colors:
  front: FF4814
  hover: B22D07
  back: FF5B2D
  compl1: 00B27F
  compl2: 14FFBB
